name: Changesets

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

env:
  CI: true

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.1
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lenmor-invoicesimple'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Configure npm authentication
        run: |
          echo "@lenmor-invoicesimple:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create a PR with changesets
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     commit: "chore: update versions"
      #     title: "chore: update versions"
      #     publish: pnpm ci:publish
      #     createGithubReleases: true
      # publish with changesets
      - name: Publish packages with changesets
        run: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESET_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
